services:
  backend:
    image: iamgodot/pistachio
    environment:
      - PISTACHIO_SETTINGS=ProdSettings
      - SQLALCHEMY_DATABASE_URI=mysql+mysqldb://root:root@db/pistachio
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - CHATPDF_API_KEY=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_REGION_NAME=
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pistachio
  app:
    image: iamgodot/pistachio-ui
    ports:
      - "8000:80"
