name: test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'
      - 'infra/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'
      - 'infra/**'
      - '*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pdm && pdm install -p backend
      - run: make test
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: |
            ghcr.io/iamgodot/pistachio:latest
            ghcr.io/iamgodot/pistachio:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: https://7d95d364-5863-4782-af23-87f98383522b.vultr-k8s.com:6443
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          namespace: default
          manifests: |
            infra/backend.yml
          images: |
            ghcr.io/iamgodot/pistachio:${{ github.sha }}
