name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infra/**'
      - 'tests/**'
      - 'docs/**'
      - '*.md'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: iamgodot/pistachio
