name: Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'
      - 'infra/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'frontend/**'
      - 'infra/**'
      - 'docs/**'
      - '*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install pdm && pdm install -p backend
      - run: cd backend && make test
